### ISSUE TITLE
3. view customers testimonials

### ISSUE THREAD

**Issue by shatfield4** [shatfield4/iCyberSecurity#3]
As a product seller, I want my customers to see other customers satisfied testimonials.

Detailed Description: A page for the customers to see what other customers experienced or thought before and/or after using the products. Purpose of the page is to make people want to trust and use the products and to also urge them to share their own experience afterwards. 

Tasks:
1.Create and display on QT a list of testimonials. 
2. Each testimonials should include name/nickname of the person and when they submitted the testimonial.
3. Have a section on the bottom mentioning where people can submit their testimonials.

Done: When the page is clear and easy to read the testimonials.

**Comment by ayako54** [comment]
Testimonials:

Bob S.
8/10/2019
Our company has a large IT environment that requires a very reliable security system. iCyberSecurity is constantly updating their systems to oppose new threats and to make the software more easier to use. We have been using iCyberSecurity for years and never had to look back.

Maria H.
7/12/2019
I have been only using iCyberSecurity for couple of months but I clearly see the difference in my computers performance. They have a cleanup service to remove any unnecessary cache etc. to boost up your computer performance and only once using it I have more space on my drive and faster performance. There are other free cleanup services that I have also used before but iCyberSecurity constantly updates it to help get rid of any additional stuff and upgrade your computer's environment. I am satisfied with their service and plan to continue using their software.

Karen W.
2/20/2019
Our computer had recently been attacked by a virus and ended up called iCyberSecurity for help. I am glad we have chosen them because of their 24/7 help service and easy to understand instructions by their IT supports. Their fast and reliable support are the best so far from our experience and we love it. Will continue to support them.
